# Numpy 1 - *Python and Grid-based Gambling*

***You work for a casino that is piloting new gambling machines.  The casino has 6 rows of the new machines; each row contains 6 machines. Each machine in this 6x6 grid will allow a no more than 10 jackpot prizes per hour. The casino asks you to monitor and log the machines over time; this requires various tasks outlined in the sections below.***

## Part 1 -- Create

(10 points)  You've been asked to simulate **12 hours** of data collection, where the number of each machine's **jackpots per hour** are recorded.

Create a 3D structure capable of storing the hourly totals for each machine in the 6x6 grid; fill this structure with random integer values between 0 and 10 (inclusive) to indicate how many jackpots per machine happened.

Your 3D data structure should be able to hold 12 copies of 6x6 values. Print your structure.

In [1]:
import numpy as np

# create 3D array for 6 rows of 6 machines and simulate jackpots for 12 hours
# jackpots simulated by random integers from 0-10 representing number of 
# jackpots per hour
jackpot_arr = np.random.randint(0,11, size=(12,6,6))

# print 3d array
print(jackpot_arr)

[[[ 4  1  0  6  3  6]
  [ 7  3  6  6  7  0]
  [ 8  1  4  2 10 10]
  [ 6  9  0  8  7  6]
  [ 4  2 10  0  5  7]
  [ 2  6 10  2  0  7]]

 [[ 3  3  6  1 10  1]
  [ 4 10  3  4  9  4]
  [ 1  0 10  4  2  3]
  [ 1  7  2 10  0  5]
  [ 0  7  8  7  9  9]
  [ 4  2  3  4  3  3]]

 [[ 6  5  3  1  6  6]
  [ 2  1  8  8  3  1]
  [ 7  2  9  2  8 10]
  [ 2  6  0  2  6  8]
  [ 4  7  5  7  6  4]
  [ 1  8  9  4  5  2]]

 [[10  1  5  1  9  4]
  [10  8  7  9  5  2]
  [ 3  3  6  9  0  1]
  [ 2  1  1  1  4  7]
  [ 7  4  9  3  2  8]
  [ 6  5 10  7  5  1]]

 [[ 7 10  2 10  4  4]
  [10  3  6  3  4  9]
  [ 9  7  4  4  9  0]
  [ 4  0  3  1  1  3]
  [ 3  9  7  2 10  3]
  [ 8  9  8  7  7  6]]

 [[ 1 10  7  2  0  5]
  [ 3  4  8  9  4  0]
  [ 5  6  0  3  5  2]
  [ 6  0  3  4  9  7]
  [ 5  7  4  5  3 10]
  [ 9  0  2 10  4  4]]

 [[ 3  5  5  8  9  2]
  [ 7  4  0  3  4  3]
  [ 3  3  0  7  2  2]
  [ 4  0 10  6  8  9]
  [10 10  7  4  5  1]
  [ 4  1  6  4  0  2]]

 [[ 6 10  6  2  1  5]
  [ 1  5  4  3  7 10]
  [ 4  0  6  1  0 

## Part 2 -- Write to File

(15 points) Write a function that takes (1) a filename and (2) a 3D data structure; this function should write the contents of the 3D structure to the specified file. Use any file format or any module you wish.  Run your function with an appropriate filename and the 3D structure from Part #1.

In [2]:
def datasave_func(fname, data):
  '''
  Function to save NumPy array as binary .npy file using NumPy "save" function.
  
  PARAMETERS
  -----------
  fname : string
      filename or path
  data : array
      array of any shape

  '''
  # call NumPy function to save any array to .npy file
  np.save(fname, data)

# creating a filename variable with .npy extension for saving 3d data structure
# to working directory
filename = 'jackpot_file.npy'

# calling function created above to save data structure created in part 1
datasave_func(filename, jackpot_arr)


## Part 3 -- Read from File

(15 points) Write a function that takes a filename, opens it, and returns the 3D structure saved inside the specified file.  Call your function using the filename from Part 2 and save the results into a new variable. Print the contents of this variable. 

In other words, your function should open what your function in Part 2 has saved.

In [3]:
def dataload_func(fname):
  '''
  Function to load binary .npy file as NumPy ndarray using the NumPy "load" function.
  
  PARAMETERS
  -----------
  fname : string
      filename or path
  
  RETURNS
  --------
  NumPy ndarray

  '''
  # call NumPy function to load .npy file and return array
  return np.load(fname)



# open data file created in part 2 as new array
# using previous filename variable form part 2
new_jackpot_arr = dataload_func(filename)

# test to compare original array to new array with boolean
comparison = jackpot_arr == new_jackpot_arr

# print overall result of comparison boolean array
print('Is the new array the same as the old array (True or False)?\n', comparison.all(), '\n')

# print new array
print(new_jackpot_arr)

Is the new array the same as the old array (True or False)?
 True 

[[[ 4  1  0  6  3  6]
  [ 7  3  6  6  7  0]
  [ 8  1  4  2 10 10]
  [ 6  9  0  8  7  6]
  [ 4  2 10  0  5  7]
  [ 2  6 10  2  0  7]]

 [[ 3  3  6  1 10  1]
  [ 4 10  3  4  9  4]
  [ 1  0 10  4  2  3]
  [ 1  7  2 10  0  5]
  [ 0  7  8  7  9  9]
  [ 4  2  3  4  3  3]]

 [[ 6  5  3  1  6  6]
  [ 2  1  8  8  3  1]
  [ 7  2  9  2  8 10]
  [ 2  6  0  2  6  8]
  [ 4  7  5  7  6  4]
  [ 1  8  9  4  5  2]]

 [[10  1  5  1  9  4]
  [10  8  7  9  5  2]
  [ 3  3  6  9  0  1]
  [ 2  1  1  1  4  7]
  [ 7  4  9  3  2  8]
  [ 6  5 10  7  5  1]]

 [[ 7 10  2 10  4  4]
  [10  3  6  3  4  9]
  [ 9  7  4  4  9  0]
  [ 4  0  3  1  1  3]
  [ 3  9  7  2 10  3]
  [ 8  9  8  7  7  6]]

 [[ 1 10  7  2  0  5]
  [ 3  4  8  9  4  0]
  [ 5  6  0  3  5  2]
  [ 6  0  3  4  9  7]
  [ 5  7  4  5  3 10]
  [ 9  0  2 10  4  4]]

 [[ 3  5  5  8  9  2]
  [ 7  4  0  3  4  3]
  [ 3  3  0  7  2  2]
  [ 4  0 10  6  8  9]
  [10 10  7  4  5  1]
  [ 4  1  6  4  0 

## Part 4 -- Averages

(15 points) Write a function that takes a 3D data structure and returns a 6x6 2D structure, where each value is the average of the hourly grid values *per machine*. Call this function using the data from Part 1; print the results.

In [4]:
def mean3d_func(data):
  '''
  Function to calculate averages of third dimension in 3D array and return 2D 
  array of means.
  
  PARAMETERS
  -----------
  data : array
      3D array
  
  RETURNS
  --------
  NumPy ndarray

  '''
  # call NumPy function on 3rd dimension (axis 2) and return 2D array of means
  # using NumPy "mean" function
  return np.mean(data, axis=0)



# call function created aboe to calculate average jackpots of simulated jackpots 
# for each machine over 12 hour period
jackpot_mean_arr = mean3d_func(jackpot_arr)

# print means and round to 3 decimal places for readability
print(jackpot_mean_arr.round(3))

[[4.917 5.5   4.583 3.583 5.083 3.75 ]
 [6.    5.417 4.75  6.333 6.083 3.667]
 [5.583 3.25  4.5   3.5   4.917 4.   ]
 [4.25  4.667 3.583 4.417 4.75  5.667]
 [4.75  5.833 5.917 4.167 6.    5.25 ]
 [5.833 5.    5.75  4.5   4.75  4.833]]


## Part 5 -- Averages (Constrained)

(15 points) A coworker training you casually mentions that occurences of 0s in the jackpot hourly totals imply the machine was disabled and out of order for that hour.

Write a function that takes a 3D structure and returns a 6x6 2D structure, where each value is the average of the **non-zero** hourly grid values per machine. If all hourly values for a single machine are 0, return -1 for that machine's totals.

Call this function using the data from Part 1; print the results.

In [47]:
def nzmean3d_func(data):
  '''
  Function to calculate averages ignoring non-zero values of third dimension in 
  3D array and return 2D array of means. When calculated mean=0, result returned 
  as -1.
  
  PARAMETERS
  -----------
  data : array
      3D array
  
  RETURNS
  --------
  NumPy 2D ndarray
  
  '''
  # calculate constrained mean of jackpot simulation over 12 hours by calling
  # NumPy "sum" function along 3rd dimension then divide using NumPy "count_nonzero"
  # function by the number of non-zero elements along 3rd dimension for constrained mean

  # create empty 6x6 array with uninitialized values; same shape as mean of input array
  nzm = np.empty(shape=(6,6))

  # create boolean mask capturing all values in input array with one or more non-zero values along axis 0
  mask = np.count_nonzero(data, axis=0) > 0

  # modify empty array with constrained mean values; for all values in empty array corresponding to indices
  # of non-zero counts of one or more...input mean along axis 0 (not including zero values)
  nzm[mask] = np.sum(data, axis=0)[mask] / np.count_nonzero(data, axis=0)[mask]

  # for all values in input array with all zeros along axis 0, input -1 flag
  nzm[~mask] = -1

  # return 2d array of contrained means (not including zero values) and -1 flag for all zeros
  return nzm



# calculate constrained average jackpots of each machine over 12 hour period
jackpot_constrainedmean_arr = nzmean3d_func(jackpot_arr)

# print results of constrained means, rounding to 3 decimals for readability
print(jackpot_constrainedmean_arr.round(3))


# testing machine on first row and column with 0 hourly jackpots
# copy 3d array
test1 = jackpot_arr.copy()
# change first row, first column, all 3rd dimension values to 0
test1[:,0,0] = 0
# calling function from above, should give -1 in position 0,0
print('\nTest 1: -1 in 0,0 position')
print('\n', nzmean3d_func(test1).round(3))


# testing input with all machines having 0 hourly jackpots; should give 2d array
# of all -1 values
test2 = np.zeros((12,6,6))
print('\nTest 2: -1 in all positions')
print('\n', nzmean3d_func(test2))

[[4.917 6.    5.    3.909 5.545 4.091]
 [6.    5.417 5.7   6.333 6.083 4.4  ]
 [5.583 4.333 6.    3.818 5.9   4.8  ]
 [4.25  6.222 4.3   4.818 5.7   5.667]
 [5.182 6.364 5.917 4.545 6.    5.727]
 [5.833 6.    6.273 4.909 5.7   5.273]]

Test 1: -1 in 0,0 position

 [[-1.     6.     5.     3.909  5.545  4.091]
 [ 6.     5.417  5.7    6.333  6.083  4.4  ]
 [ 5.583  4.333  6.     3.818  5.9    4.8  ]
 [ 4.25   6.222  4.3    4.818  5.7    5.667]
 [ 5.182  6.364  5.917  4.545  6.     5.727]
 [ 5.833  6.     6.273  4.909  5.7    5.273]]

Test 2: -1 in all positions

 [[-1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.]]


## Part 6 -- Targeting Machines

(10 points) The company is very happy with your ability to create averages of their machines' jackpots.  They instruct you to disable any machine that averaged at least 7 jackpots during the initial 12 hour period because it's "too hot" and to run your simulation again on the remaining machines.

In other words, repeat Part 1 for another 12 hour period by creating another 3D structure of randomized results 0-10, where the "too hot" machines from the first simulation are also disabled and forced to appear as 0s at every hour. 

Show your results by printing the indices of the "too hot" machines and by printing the final 3D structure.

In [48]:
# create new jackpot simulation for another 12 hour period;
# 6 machines on 6 rows for 12 hours (same methods as part 1 above)
next_jackpot_arr = np.random.randint(0,11, size=(12,6,6))


# find indices of "hot" machines (at least 7 jackpots) using constrained
# means function from part 5 above
# "argwhere" function returns indices of input array; here input array is mask
# of constrained means where the number of jackpots over 12 hours is 7 or greater
hot_idx = np.argwhere(jackpot_constrainedmean_arr >= 7)


# disable hot machines found in new simulation by changing to zero
# for second 12 hour time period; use indices determined in step above to index
# simulation and replace hot machines with 0 ("hot" rows, "hot" columns, all 12 hours)
next_jackpot_arr[:, hot_idx[:,0], hot_idx[:,1]] = 0


# print indices and final modified second simulation
print('Indices of hot machines in the first simulation: \n', hot_idx)
print('\nSecond simulation without "hot" machines: \n', next_jackpot_arr)

Indices of hot machines in the first simulation: 
 []

Second simulation without "hot" machines: 
 [[[ 8  2  2  0  4  3]
  [ 9  7  0  4  4  2]
  [10 10  9  5  6  7]
  [ 3  4  2 10  4  1]
  [ 2  9  0  5 10  1]
  [ 7  6  1  0  6 10]]

 [[ 3  1  9 10  8  9]
  [ 8  4  4  3  9  9]
  [ 0  7  6  5  3  1]
  [ 2  9  4  4 10  7]
  [ 9  1  8  6  3  9]
  [ 4  1  4  8  1  1]]

 [[ 0  9  2  0  3  2]
  [ 6  7  1 10 10  6]
  [10  5  0 10  8  0]
  [ 2  3  8  6 10  1]
  [ 2  4 10 10  6  5]
  [ 9  9  2  7  4  7]]

 [[ 4  2  2  5  0  8]
  [ 0  3  1  3  6  7]
  [ 1  0  3  4  7  6]
  [ 6  7  1  5  5  4]
  [ 8  9  4  2  5  4]
  [ 3  6  0  8  6  5]]

 [[ 8  1  5  1  0  9]
  [ 5  8  3  8  5  3]
  [ 8  6  9  9  5  1]
  [ 5 10  7  7  1  3]
  [ 3  8  0  2  7  6]
  [ 7  0  0  4 10  5]]

 [[ 5  6  3  1 10  4]
  [10  5 10  3  2  5]
  [ 3 10  1  1  6  4]
  [ 9  4  2  2  6  0]
  [ 0  7  0  6  3  7]
  [ 9  7  1  1  3  6]]

 [[ 0  3  2  4  1  2]
  [ 6 10  0  9  6  7]
  [ 2  8  2  1 10  9]
  [ 4  8 10  8  7  1]
  [ 8  9 